# .gitlab-ci.yml
stages:
  - build
  - deploy

variables:
  # GitLab Container Registry URL
  REGISTRY_URL: $CI_REGISTRY
  IMAGE_NAME: $CI_REGISTRY_IMAGE
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA

# Build Docker image using Kaniko
build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  variables:
    # CRITICAL: This fixes the speed problems on NRP!
    GODEBUG: "http2client=0"
  script:
    - echo "Building axolotl Docker image with Kaniko..."
    - mkdir -p /kaniko/.docker
    - |
      echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n $CI_REGISTRY_USER:$CI_REGISTRY_PASSWORD | base64)\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor 
      --cache=true 
      --push-retry=10 
      --context $CI_PROJECT_DIR 
      --dockerfile $CI_PROJECT_DIR/docker/Dockerfile 
      --destination $IMAGE_NAME:$IMAGE_TAG
      --destination $IMAGE_NAME:latest
  only:
    - main
    - master
    - development

# Generate Kubernetes manifest
generate-manifest:
  stage: deploy
  image: alpine:latest
  before_script:
    - mkdir -p k8s
  script:
    - echo "Generating Kubernetes manifest for axolotl..."
    - |
      cat > k8s/axolotl-job.yaml << EOF
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: axolotl-${CI_COMMIT_SHORT_SHA}
        namespace: braingeneers
      spec:
        backoffLimit: 0
        template:
          spec:
            containers:
            - name: axolotl
              image: ${IMAGE_NAME}:${IMAGE_TAG}
              imagePullPolicy: Always
              command: ["/bin/bash", "-c"]
              args:
                - |
                  export AWS_REQUEST_CHECKSUM_CALCULATION=when_required
                  export AWS_RESPONSE_CHECKSUM_VALIDATION=when_required
                  cd /workspace
                  python /workspace/src/main.py /workspace/config/experiment_config.yaml
              resources:
                requests:
                  cpu: "4"
                  memory: "16Gi"
                limits:
                  cpu: "4"
                  memory: "16Gi"
              volumeMounts:
              - name: output-volume
                mountPath: /workspace/output
              - name: prp-s3-credentials
                mountPath: "/root/.aws/credentials"
                subPath: "credentials"
              - name: config-volume
                mountPath: /workspace/config
            restartPolicy: Never
            imagePullSecrets:
            - name: gitlab-registry
            volumes:
            - name: output-volume
              persistentVolumeClaim:
                claimName: demeter-output-pvc
            - name: prp-s3-credentials
              secret:
                secretName: prp-s3-credentials
                defaultMode: 256
            - name: config-volume
              configMap:
                name: axolotl-config
      EOF
    - echo "Manifest generated successfully"
  artifacts:
    paths:
      - k8s/axolotl-job.yaml
    expire_in: 1 week
  only:
    - main
    - master