# k8s/cortical-theta-experiment.yaml
# Example: Completely different experiment using same Docker image
# Analysis of cortical theta oscillations in a different sample
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: axolotl-cortical-theta-config
  namespace: braingeneers
  labels:
    app: axolotl
    experiment: cortical-theta-2024
data:
  cortical_theta_experiment.yaml: |
    # Cortical Theta Oscillations Experiment
    experiment:
      name: "cortical_theta_analysis_2024"
      s3_output_base: "s3://braingeneers/oscillations/results/cortical-theta-2024/"
      description: "Theta rhythm analysis in cortical organoids"

    # Completely different oscillation types - focused on theta
    oscillation_types:
      # Theta oscillations: 4-12 Hz
      theta_oscillations:
        narrowband_key: "theta_narrow"
        wideband_key: "theta_wide"  
        low_threshold: 2.0
        high_threshold: 3.5
        min_duration: 100          # Longer for theta (100ms)
        max_duration: 2000         # Much longer (2 seconds)
        require_sharp_wave: false
        
      # Slow gamma: 30-50 Hz (often coupled with theta)
      slow_gamma:
        narrowband_key: "slow_gamma"
        wideband_key: "gamma_broad"
        low_threshold: 2.5
        high_threshold: 4.0
        min_duration: 50
        max_duration: 500
        require_sharp_wave: false

    # Different frequency bands for theta analysis
    processing:
      frequency_bands:
        - name: "theta_narrow"
          low: 6
          high: 10
        - name: "theta_wide"
          low: 4
          high: 12
        - name: "slow_gamma"
          low: 30
          high: 50
        - name: "gamma_broad"
          low: 25
          high: 60
      
      analysis_window:
        start: 0
        length: null

    visualization:
      channels_per_plot: 4
      ripples_per_channel: 20     # More events for theta
      time_window: 2.0            # Longer time window for theta
      save_format: ["png"]

    # Different sample - cortical organoids instead of hippocampal
    samples:
      - name: "2024-02-10-cortical-organoid-batch3"
        description: "Cortical organoids 60 days in vitro"
        conditions:
          control:
            description: "Standard media"
            files:
              h5: "s3://braingeneers/organoids/2024-02-10-batch3/control/recording.h5"
              zip: "s3://braingeneers/organoids/2024-02-10-batch3/control/spikes.zip"
              npz: "s3://braingeneers/organoids/2024-02-10-batch3/control/lfp.npz"
          
          glutamate:
            description: "Glutamate stimulation"
            files:
              h5: "s3://braingeneers/organoids/2024-02-10-batch3/glutamate/recording.h5"
              zip: "s3://braingeneers/organoids/2024-02-10-batch3/glutamate/spikes.zip"
              npz: "s3://braingeneers/organoids/2024-02-10-batch3/glutamate/lfp.npz"

    advanced_processing:
      enable_caching: true
      statistical_tests:
        - "mann_whitney"
      aggregate_statistics: true
      generate_summary_plots: true

---
apiVersion: batch/v1
kind: Job
metadata:
  name: axolotl-cortical-theta-2024-02
  namespace: braingeneers
  labels:
    app: axolotl
    experiment: cortical-theta-2024
spec:
  backoffLimit: 1
  template:
    spec:
      containers:
      - name: axolotl
        image: registry.gitlab.com/braingeneers/axolotl:latest  # SAME IMAGE AS HIPPOCAMPAL EXPERIMENT!
        imagePullPolicy: Always
        
        command: ["/bin/bash", "-c"]
        args:
          - |
            export AWS_REQUEST_CHECKSUM_CALCULATION=when_required
            export AWS_RESPONSE_CHECKSUM_VALIDATION=when_required
            cd /workspace
            echo "Starting cortical theta oscillations analysis..."
            echo "Sample: 2024-02-10-cortical-organoid-batch3"
            echo "Conditions: control, glutamate"
            echo "Oscillations: theta, slow gamma"
            python /workspace/src/main.py ${EXPERIMENT_CONFIG_PATH}
        
        env:
        - name: EXPERIMENT_CONFIG_PATH
          value: "/workspace/config/cortical_theta_experiment.yaml"  # DIFFERENT CONFIG FILE!
        - name: PYTHONPATH
          value: "/workspace/src"
        
        resources:
          requests:
            cpu: "4"
            memory: "16Gi"
          limits:
            cpu: "6"
            memory: "24Gi"
        
        volumeMounts:
        - name: output-volume
          mountPath: /workspace/output
        - name: prp-s3-credentials
          mountPath: "/root/.aws/credentials"
          subPath: "credentials"
        - name: config-volume
          mountPath: /workspace/config
      
      restartPolicy: Never
      imagePullSecrets:
      - name: gitlab-registry
      
      volumes:
      - name: output-volume
        persistentVolumeClaim:
          claimName: demeter-output-pvc
      - name: prp-s3-credentials
        secret:
          secretName: prp-s3-credentials
          defaultMode: 256
      - name: config-volume
        configMap:
          name: axolotl-cortical-theta-config  # DIFFERENT CONFIGMAP!
