# k8s/experiment_config.yaml
# Example configuration for axolotl oscillation detection pipeline

experiment:
  name: "hippocampal_oscillations_study"
  s3_output_base: "s3://braingeneers/oscillations/results/"
  description: "Multi-type oscillation detection in hippocampal cultures"

# Define different oscillation types with their detection parameters
oscillation_types:
  ripples:
    narrowband_key: "ripples_narrow"   # 110-200 Hz for ripple detection
    wideband_key: "ripples_wide"       # 80-200 Hz for broader ripple context
    low_threshold: 3.0                 # Starting/ending threshold (std dev)
    high_threshold: 5.0                # Peak threshold (std dev)
    min_duration: 20                   # Minimum duration (ms)
    max_duration: 150                  # Maximum duration (ms)
    require_sharp_wave: false          # Ripples can occur independently
    
  sharp_wave_ripples:
    narrowband_key: "swr_ripples"      # 110-200 Hz for ripple component
    wideband_key: "swr_broad"          # 80-250 Hz for broader SWR context
    low_threshold: 3.5                 # Starting/ending threshold (std dev)
    high_threshold: 5.0                # Peak threshold (std dev)
    min_duration: 20                   # Minimum duration (ms)
    max_duration: 200                  # Maximum duration (ms)
    require_sharp_wave: true           # Must have coincident sharp wave
    sharp_wave_window: 50              # Time window for sharp wave search (±ms)
    
  fast_ripples:
    narrowband_key: "hfo_narrow"       # 250-400 Hz for HFO detection
    wideband_key: "hfo_wide"           # 200-450 Hz for broader HFO context
    low_threshold: 3.0                 # Starting/ending threshold (std dev)
    high_threshold: 4.5                # Peak threshold (std dev)
    min_duration: 10                   # Minimum duration (ms)
    max_duration: 100                  # Maximum duration (ms)
    require_sharp_wave: false          # HFOs don't require sharp waves

# Processing parameters
processing:
  # Frequency bands for filtering (matched to oscillation detection needs)
  frequency_bands:
    - name: "sharpWave"
      low: 1
      high: 30
    - name: "ripples_narrow"  
      low: 110
      high: 200
    - name: "ripples_wide"
      low: 80
      high: 200
    - name: "swr_ripples"
      low: 110
      high: 200
    - name: "swr_broad"
      low: 80
      high: 250
    - name: "hfo_narrow"
      low: 250
      high: 400
    - name: "hfo_wide"
      low: 200
      high: 450
  
  # Analysis window settings
  analysis_window:
    start: 0              # Start time (seconds, 0 = beginning)
    length: null          # Duration (seconds, null = entire recording)

# Visualization parameters
visualization:
  channels_per_plot: 5         # Number of channels per visualization plot
  ripples_per_channel: 10      # Max ripples to show per channel
  time_window: 0.3             # Time window around each ripple (seconds)
  save_format: ["png", "svg"]  # Output formats for plots

# Sample definitions with different experimental conditions
samples:
  - name: "culture_001"
    description: "Primary hippocampal culture, 21 DIV"
    conditions:
      baseline:
        description: "Control recording in normal ACSF"
        files:
          h5: "s3://braingeneers/datasets/culture_001/baseline/raw_data.h5"
          zip: "s3://braingeneers/datasets/culture_001/baseline/spike_data.zip" 
          npz: "s3://braingeneers/datasets/culture_001/baseline/lfp_data.npz"
      
      drug_treatment:
        description: "Recording after 30min 4-AP treatment"
        files:
          h5: "s3://braingeneers/datasets/culture_001/4ap_treatment/raw_data.h5"
          zip: "s3://braingeneers/datasets/culture_001/4ap_treatment/spike_data.zip"
          npz: "s3://braingeneers/datasets/culture_001/4ap_treatment/lfp_data.npz"
  
  - name: "culture_002"
    description: "Primary hippocampal culture, 28 DIV"
    conditions:
      baseline:
        description: "Control recording in normal ACSF"
        files:
          h5: "s3://braingeneers/datasets/culture_002/baseline/raw_data.h5"
          zip: "s3://braingeneers/datasets/culture_002/baseline/spike_data.zip"
          npz: "s3://braingeneers/datasets/culture_002/baseline/lfp_data.npz"
      
      drug_treatment:
        description: "Recording after 30min 4-AP treatment"  
        files:
          h5: "s3://braingeneers/datasets/culture_002/4ap_treatment/raw_data.h5"
          zip: "s3://braingeneers/datasets/culture_002/4ap_treatment/spike_data.zip"
          npz: "s3://braingeneers/datasets/culture_002/4ap_treatment/lfp_data.npz"

# Optional: Advanced processing parameters
advanced_processing:
  # NPZ caching settings
  enable_caching: true          # Use NPZ files to avoid re-computation
  cache_s3_prefix: "cache/"     # S3 prefix for cached results
  
  # Cleanup settings
  cleanup_temp_files: true      # Remove temporary files after processing
  
  # Statistical analysis settings
  statistical_tests:
    - "wilcoxon"                # Wilcoxon signed-rank test
    - "mann_whitney"            # Mann-Whitney U test
  
  # Output organization
  aggregate_statistics: true    # Generate cross-condition statistics
  generate_summary_plots: true  # Create aggregate visualization plots