# k8s/hippocampal-oscillations-job.yaml
# Kubernetes Job for hippocampal oscillations experiment
# Sample: 2023-12-03-e-Hc112823_avv9hckcr1 (baseline, optogenetics, kainic acid)
apiVersion: batch/v1
kind: Job
metadata:
  name: axolotl-hippocampal-oscillations-2023-12-03
  namespace: braingeneers
  labels:
    app: axolotl
    component: oscillation-detector
    experiment: hippocampal-oscillations-2023
    sample: "2023-12-03-e-Hc112823_avv9hckcr1"
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: axolotl
        component: oscillation-detector
        experiment: hippocampal-oscillations-2023
    spec:
      containers:
      - name: axolotl
        image: registry.gitlab.com/braingeneers/axolotl:latest
        imagePullPolicy: Always
        
        # Main command and arguments
        command: ["/bin/bash", "-c"]
        args:
          - |
            export AWS_REQUEST_CHECKSUM_CALCULATION=when_required
            export AWS_RESPONSE_CHECKSUM_VALIDATION=when_required
            cd /workspace
            echo "Starting hippocampal oscillations analysis..."
            echo "Sample: 2023-12-03-e-Hc112823_avv9hckcr1"
            echo "Conditions: baseline, optogenetics, kainic acid"
            echo "Oscillations: ripples, sharp wave ripples, fast ripples/HFOs"
            echo "Configuration: ${EXPERIMENT_CONFIG_PATH}"
            python /workspace/src/main.py ${EXPERIMENT_CONFIG_PATH}
        
        # Environment variables
        env:
        - name: EXPERIMENT_CONFIG_PATH
          value: "/workspace/config/hippocampal_oscillations_experiment.yaml"
        - name: PYTHONPATH
          value: "/workspace/src"
        - name: EXPERIMENT_NAME
          value: "hippocampal_oscillations_multimodal_2023"
        - name: SAMPLE_NAME
          value: "2023-12-03-e-Hc112823_avv9hckcr1"
        
        # Resource requirements - increased for multi-condition analysis
        resources:
          requests:
            cpu: "6"
            memory: "24Gi"
          limits:
            cpu: "8"
            memory: "32Gi"
        
        # Volume mounts
        volumeMounts:
        # Output directory for results
        - name: output-volume
          mountPath: /workspace/output
        
        # S3 credentials for data access
        - name: prp-s3-credentials
          mountPath: "/root/.aws/credentials"
          subPath: "credentials"
        
        # Experiment configuration
        - name: config-volume
          mountPath: /workspace/config
      
      # Pod restart policy
      restartPolicy: Never
      
      # Image pull secrets for private registry
      imagePullSecrets:
      - name: gitlab-registry
      
      # Volumes
      volumes:
      # Persistent volume for output storage
      - name: output-volume
        persistentVolumeClaim:
          claimName: demeter-output-pvc
      
      # S3 credentials secret
      - name: prp-s3-credentials
        secret:
          secretName: prp-s3-credentials
          defaultMode: 256
      
      # Configuration from ConfigMap
      - name: config-volume
        configMap:
          name: axolotl-hippocampal-config
