apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jdsr-oscillations-output-pvc
  namespace: braingeneers
  labels:
    app: axolotl
    experiment: jdsr-oscillations
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: rook-cephfs
