# k8s/job.yaml
# Kubernetes Job template for running axolotl oscillation detection pipeline
apiVersion: batch/v1
kind: Job
metadata:
  name: axolotl-oscillation-detection
  namespace: braingeneers
  labels:
    app: axolotl
    component: oscillation-detector
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: axolotl
        component: oscillation-detector
    spec:
      containers:
      - name: axolotl
        image: registry.gitlab.com/braingeneers/axolotl:latest
        imagePullPolicy: Always
        
        # Main command and arguments
        command: ["/bin/bash", "-c"]
        args:
          - |
            export AWS_REQUEST_CHECKSUM_CALCULATION=when_required
            export AWS_RESPONSE_CHECKSUM_VALIDATION=when_required
            cd /workspace
            echo "Starting axolotl oscillation detection pipeline..."
            python /workspace/src/main.py ${EXPERIMENT_CONFIG_PATH:-/workspace/config/experiment_config.yaml}
        
        # Environment variables
        env:
        - name: EXPERIMENT_CONFIG_PATH
          value: "/workspace/config/experiment_config.yaml"
        - name: PYTHONPATH
          value: "/workspace/src"
        
        # Resource requirements
        resources:
          requests:
            cpu: "4"
            memory: "16Gi"
          limits:
            cpu: "4"
            memory: "16Gi"
        
        # Volume mounts
        volumeMounts:
        # Output directory for results
        - name: output-volume
          mountPath: /workspace/output
        
        # S3 credentials for data access
        - name: prp-s3-credentials
          mountPath: "/root/.aws/credentials"
          subPath: "credentials"
        
        # Experiment configuration
        - name: config-volume
          mountPath: /workspace/config
      
      # Pod restart policy
      restartPolicy: Never
      
      # Image pull secrets for private registry
      imagePullSecrets:
      - name: gitlab-registry
      
      # Volumes
      volumes:
      # Persistent volume for output storage
      - name: output-volume
        persistentVolumeClaim:
          claimName: demeter-output-pvc
      
      # S3 credentials secret
      - name: prp-s3-credentials
        secret:
          secretName: prp-s3-credentials
          defaultMode: 256
      
      # Configuration from ConfigMap
      - name: config-volume
        configMap:
          name: axolotl-config